RIDER_ARRIVAL = 'rider_arrival'
RIDER_LOST = 'rider_lost'
RIDE_COMPLETION = 'ride_completion'
RELOCATION_START = 'relocation_start'
RELOCATION_COMPLETION = 'relocation_completion'
RIDE_START = 'ride_start'
TIME_BLOCK_BOUNDARY = 'time_block_boundary'